### ISSUE TITLE
Merger avec l'outil JeedomPluginSkeletonGenerator

### ISSUE THREAD

**Issue by slobberbone** [Jeedom-Plugins-Extra/extra-tools#3]
Merger avec l'outil de @Sylvaner : https://github.com/Sylvaner/JeedomPluginSkeletonGenerator

**Comment by Sylvaner** [comment]
Si on peut mettre du python je pourrais facilement intégrer les fonctions.
Après on part d'un template comme actuellement où on construit le squelette à partir de rien ?
Le but final est il d'offrir un outil pour construire un plugin au départ ou de pouvoir être utilisé sur un existant ?

**Comment by guenneguezt** [comment]
Je pense qu'il faut un truc qui fonctionne sur tout os avec le moins possible de truc à installer (par exemple python)Après j'ai pas non plus la solution miracle ;-)

**Comment by Sylvaner** [comment]
On peut essayer en shell mais j'ai peur qu'on est des commandes sed awk, fond illisibles

**Comment by slobberbone** [comment]
@Sylvaner non allons-y pour python, c juste que je ne connais pas et que j'avais les batch de chercher insérer/remplacer ....
le plus important ce sont les fichiers à intégrer et les annotations à mettre dnas le plugin-Template pour permettre l'insertion de code !

**Comment by Sylvaner** [comment]
Du coup on part avec un le template, ou on fait une copie de plugin-Template on remplace tous les champs par des annotations ?

**Comment by slobberbone** [comment]
On part du plugin-Template, mais c bien le plugin-Template qu'on modifie en direct !
Comme ça dès qu'il y a des améliorations dans le plugin-template on en loupera pas !
